winget install Eraser.Eraser
winget install Git.Git
winget install GitHub.Atom
winget install JetBrains.IntelliJIDEA.Community
winget install JetBrains.PyCharm.Community
winget install LibreOffice.LibreOffice
winget install Microsoft.OpenJDK.16
winget install Microsoft.Teams
winget install Microsoft.VisualStudioCode
winget install Microsoft.WindowsTerminal
winget install MongoDB.Server
winget install Oracle.JavaRuntimeEnvironment
winget install Piriform.Recuva
winget install Piriform.Speccy
winget install Python.Python.3
winget install VideoLAN.VLC
winget install VMware.WorkstationPlayer
winget install OpenShot.OpenShot
winget install Oracle.VirtualBox
