winget install AnyDeskSoftwareGmbH.AnyDesk
winget install Axosoft.GitKraken
winget install Balena.Etcher
winget install Blade.Shadow
winget install BraveSoftware.BraveBrowser
winget install Discord.Discord
winget install Eassos.DiskGenius
winget install Electrum.Electrum
winget install Eraser.Eraser
winget install GIMP.GIMP
winget install Git.Git
winget install GitHub.Atom
winget install JetBrains.IntelliJIDEA.Community
winget install JetBrains.PyCharm.Community
winget install KDE.Kdenlive
winget install KDE.Krita
winget install LibreOffice.LibreOffice
winget install Microsoft.OpenJDK.16
winget install Microsoft.Teams
winget install Microsoft.WindowsTerminal
winget install Microsoft.VisualStudioCode
winget install MongoDB.Compass.Community
winget install MongoDB.Server
winget install OBSProject.OBSStudio
winget install Oracle.JavaRuntimeEnvironment
winget install Oracle.VirtualBox
winget install Piriform.Recuva
winget install Piriform.Speccy
winget install ProtonTechnologies.ProtonVPN
winget install Python.Python.3
winget install Ultimaker.Cura
winget install Valve.Steam
winget install VMware.WorkstationPlayer
winget install Yubico.Authenticator
